package org.linphone.incomingcall.bot.local

import android.content.Context
import android.util.Log
import com.google.gson.JsonArray
import com.google.gson.JsonObject
import com.google.gson.JsonParser
import org.linphone.incomingcall.hiva.HivaRoomClient
import java.io.File
import java.time.LocalDate
import java.time.YearMonth
import java.time.format.DateTimeFormatter
import kotlin.math.roundToLong

class LocalDataStore(context: Context) {
    private val tag = "BT_DATASTORE"
    private val root = File(context.filesDir, "local_bot_data").apply { mkdirs() }
    private val mockDir = File(root, "mock").apply { mkdirs() }
    private val cacheDir = File(root, "cache").apply { mkdirs() }
    private val outputsDir = File(root, "outputs").apply { mkdirs() }

    fun mockDirPath(): String = mockDir.absolutePath
    fun outputsDirPath(): String = outputsDir.absolutePath

    fun mockList(): JsonArray {
        val out = JsonArray()
        mockDir.listFiles()?.sortedByDescending { it.lastModified() }?.forEach { f ->
            out.add(JsonObject().apply {
                addProperty("filename", f.name)
            })
        }
        return out
    }

    fun listDatasets(): List<String> {
        val datasets = linkedSetOf<String>()
        val dayPattern = Regex("^([A-Za-z]+)-day-(\\d{4}-\\d{2}-\\d{2})-(\\d+)m$")
        val monthPattern = Regex("^([A-Za-z]+)-month-(\\d{4}-\\d{2})-(\\d+)m$")
        val dateRangePattern = Regex("^([A-Za-z]+)-date-(\\d{4}-\\d{2}-\\d{2})_(\\d{4}-\\d{2}-\\d{2})-(\\d+)m$")
        val cachePattern = Regex("^candles_(\\d+)_(\\d{4}-\\d{2}-\\d{2})$")

        fun parseName(rawName: String) {
            val name = rawName.removeSuffix(".json")
            when {
                dayPattern.matches(name) -> {
                    val m = dayPattern.find(name) ?: return
                    datasets += "${m.groupValues[1]}-day-${m.groupValues[2]}"
                }
                monthPattern.matches(name) -> {
                    val m = monthPattern.find(name) ?: return
                    datasets += "${m.groupValues[1]}-month-${m.groupValues[2]}"
                }
                dateRangePattern.matches(name) -> {
                    val m = dateRangePattern.find(name) ?: return
                    datasets += "${m.groupValues[1]}-date-${m.groupValues[2]}_${m.groupValues[3]}"
                }
                cachePattern.matches(name) -> {
                    val m = cachePattern.find(name) ?: return
                    datasets += "C-day-${m.groupValues[2]}"
                }
            }
        }

        mockDir.listFiles()?.forEach { parseName(it.name) }
        cacheDir.listFiles()?.forEach { parseName(it.name) }
        return datasets.toList().sortedDescending()
    }

    fun loadDatasetCandles(datasetId: String, tf: String = "1"): List<LocalCandle> {
        val dayPattern = Regex("^([A-Za-z]+)-day-(\\d{4}-\\d{2}-\\d{2})$")
        val monthPattern = Regex("^([A-Za-z]+)-month-(\\d{4}-\\d{2})$")
        val rangePattern = Regex("^([A-Za-z]+)-date-(\\d{4}-\\d{2}-\\d{2})_(\\d{4}-\\d{2}-\\d{2})$")

        val files = mutableListOf<File>()

        fun appendDay(date: String) {
            val mockFile = File(mockDir, "M-day-$date-${tf}m.json")
            if (mockFile.exists()) files += mockFile
            val cacheFile = File(cacheDir, "candles_${tf}_${date}.json")
            if (cacheFile.exists()) files += cacheFile
            // Tolerate filename variants generated by older app versions.
            mockDir.listFiles()?.forEach { f ->
                val n = f.name
                if (n == "M-day-$date-${tf}m.json") files += f
                if (n == "SH-day-$date-${tf}m.json") files += f
            }
            cacheDir.listFiles()?.forEach { f ->
                val n = f.name
                if (n == "candles_${tf}_${date}.json") files += f
            }
        }

        when {
            dayPattern.matches(datasetId) -> {
                val m = dayPattern.find(datasetId) ?: return emptyList()
                appendDay(m.groupValues[2])
            }
            monthPattern.matches(datasetId) -> {
                val m = monthPattern.find(datasetId) ?: return emptyList()
                val ym = YearMonth.parse(m.groupValues[2])
                for (d in 1..ym.lengthOfMonth()) {
                    appendDay(ym.atDay(d).format(DateTimeFormatter.ISO_DATE))
                }
            }
            rangePattern.matches(datasetId) -> {
                val m = rangePattern.find(datasetId) ?: return emptyList()
                var cursor = LocalDate.parse(m.groupValues[2])
                val end = LocalDate.parse(m.groupValues[3])
                while (!cursor.isAfter(end)) {
                    appendDay(cursor.format(DateTimeFormatter.ISO_DATE))
                    cursor = cursor.plusDays(1)
                }
            }
            else -> {
                Log.w(tag, "loadDatasetCandles unknown dataset format datasetId=$datasetId")
                return emptyList()
            }
        }

        Log.i(
            tag,
            "loadDatasetCandles dataset=$datasetId tf=$tf candidates=${files.distinctBy { it.absolutePath }.size}"
        )
        files.distinctBy { it.absolutePath }.forEach { f ->
            Log.d(tag, "candidate path=${f.absolutePath} exists=${f.exists()} size=${f.length()}")
        }

        val out = mutableListOf<LocalCandle>()
        files.distinctBy { it.absolutePath }.forEach { file ->
            try {
                val root = JsonParser.parseString(file.readText())
                if (!root.isJsonArray) return@forEach
                val arr = root.asJsonArray
                for (i in 0 until arr.size()) {
                    val o = arr[i].asJsonObject
                    val time = o.get("time")?.asLong ?: continue
                    val open = o.get("open")?.asDouble ?: continue
                    val high = o.get("high")?.asDouble ?: continue
                    val low = o.get("low")?.asDouble ?: continue
                    val close = o.get("close")?.asDouble ?: continue
                    out += LocalCandle(time, open, high, low, close)
                }
            } catch (_: Exception) {
                // Ignore corrupt files and continue with the rest.
            }
        }
        val result = out.distinctBy { it.time }.sortedBy { it.time }
        Log.i(tag, "loadDatasetCandles loaded dataset=$datasetId candles=${result.size}")
        if (dayPattern.matches(datasetId)) {
            val expected = expectedCountForTf(tf)
            if (expected != null && result.size > expected * 2) {
                Log.w(
                    tag,
                    "loadDatasetCandles count=${result.size} expected~$expected for 1 day tf=${tf}m — file likely downloaded with old resolution=1 (sub-minute). Delete mock and re-download."
                )
            }
        }
        return result
    }

    fun loadDatasetCandlesMockOnly(datasetId: String, tf: String = "1"): List<LocalCandle> {
        val dayPattern = Regex("^([A-Za-z]+)-day-(\\d{4}-\\d{2}-\\d{2})$")
        val monthPattern = Regex("^([A-Za-z]+)-month-(\\d{4}-\\d{2})$")
        val rangePattern = Regex("^([A-Za-z]+)-date-(\\d{4}-\\d{2}-\\d{2})_(\\d{4}-\\d{2}-\\d{2})$")
        val files = mutableListOf<File>()

        fun appendDay(date: String) {
            listOf(
                File(mockDir, "M-day-$date-${tf}m.json"),
                File(mockDir, "SH-day-$date-${tf}m.json")
            ).forEach { if (it.exists()) files += it }
        }

        when {
            dayPattern.matches(datasetId) -> {
                val m = dayPattern.find(datasetId) ?: return emptyList()
                appendDay(m.groupValues[2])
            }
            monthPattern.matches(datasetId) -> {
                val m = monthPattern.find(datasetId) ?: return emptyList()
                val ym = YearMonth.parse(m.groupValues[2])
                for (d in 1..ym.lengthOfMonth()) appendDay(ym.atDay(d).format(DateTimeFormatter.ISO_DATE))
            }
            rangePattern.matches(datasetId) -> {
                val m = rangePattern.find(datasetId) ?: return emptyList()
                var cursor = LocalDate.parse(m.groupValues[2])
                val end = LocalDate.parse(m.groupValues[3])
                while (!cursor.isAfter(end)) {
                    appendDay(cursor.format(DateTimeFormatter.ISO_DATE))
                    cursor = cursor.plusDays(1)
                }
            }
            else -> return emptyList()
        }

        val out = mutableListOf<LocalCandle>()
        files.distinctBy { it.absolutePath }.forEach { file ->
            try {
                val root = JsonParser.parseString(file.readText())
                if (!root.isJsonArray) return@forEach
                val arr = root.asJsonArray
                for (i in 0 until arr.size()) {
                    val o = arr[i].asJsonObject
                    val time = o.get("time")?.asLong ?: continue
                    val open = o.get("open")?.asDouble ?: continue
                    val high = o.get("high")?.asDouble ?: continue
                    val low = o.get("low")?.asDouble ?: continue
                    val close = o.get("close")?.asDouble ?: continue
                    out += LocalCandle(time, open, high, low, close)
                }
            } catch (_: Exception) {
            }
        }
        return out.distinctBy { it.time }.sortedBy { it.time }
    }

    suspend fun mockDownloadDay(gregorianDate: String, tf: String = "1"): JsonObject {
        val (from, to) = LocalBotRuntime.gregorianDayRange(gregorianDate)
        val tfs = if (tf == "1") listOf("1", "5", "15", "30", "60") else listOf(tf)
        var total = 0
        tfs.forEach { timeframe ->
            val file = File(mockDir, "M-day-$gregorianDate-${timeframe}m.json")
            val before = readCandlesIfExists(file)
            val candles = HivaRoomClient.getBars(timeframe, from, to)
            file.writeText(candlesToJson(candles))
            logDataAudit(
                source = "mockDownloadDay",
                date = gregorianDate,
                tf = timeframe,
                before = before,
                after = candles
            )
            total += candles.size
        }
        return JsonObject().apply {
            addProperty("saved", "M-day-$gregorianDate-*m.json")
            addProperty("count", total)
            addProperty("timeframes", tfs.joinToString(","))
        }
    }

    suspend fun ensureMockDayTimeframes(gregorianDate: String, missingTfs: List<String>): JsonObject {
        if (missingTfs.isEmpty()) {
            return JsonObject().apply {
                addProperty("ok", true)
                addProperty("downloaded", 0)
            }
        }
        val (from, to) = LocalBotRuntime.gregorianDayRange(gregorianDate)
        var downloaded = 0
        missingTfs.forEach { timeframe ->
            val file = File(mockDir, "M-day-$gregorianDate-${timeframe}m.json")
            val before = readCandlesIfExists(file)
            val candles = HivaRoomClient.getBars(timeframe, from, to)
            file.writeText(candlesToJson(candles))
            logDataAudit(
                source = "ensureMockDayTimeframes",
                date = gregorianDate,
                tf = timeframe,
                before = before,
                after = candles
            )
            downloaded++
        }
        return JsonObject().apply {
            addProperty("ok", true)
            addProperty("downloaded", downloaded)
            addProperty("timeframes", missingTfs.joinToString(","))
        }
    }

    suspend fun mockDownloadMonth(startDate: String, endDate: String, tf: String = "1"): JsonObject {
        val start = LocalDate.parse(startDate)
        val end = LocalDate.parse(endDate)
        var cursor = start
        var total = 0
        while (!cursor.isAfter(end.minusDays(1))) {
            val dateStr = cursor.format(DateTimeFormatter.ISO_DATE)
            val res = mockDownloadDay(dateStr, tf)
            total += res.get("count")?.asInt ?: 0
            cursor = cursor.plusDays(1)
        }
        return JsonObject().apply {
            addProperty("saved", "month-range")
            addProperty("count", total)
        }
    }

    fun cacheList(): JsonArray {
        val out = JsonArray()
        cacheDir.listFiles()?.sortedByDescending { it.lastModified() }?.forEach { f ->
            val parts = f.name.removeSuffix(".json").split("_")
            if (parts.size >= 3) {
                val tf = parts[1]
                val date = parts[2]
                val count = try {
                    JsonParser.parseString(f.readText()).asJsonArray.size()
                } catch (_: Exception) {
                    0
                }
                out.add(JsonObject().apply {
                    addProperty("tf", tf)
                    addProperty("date", date)
                    addProperty("bar_count", count)
                    addProperty("size_kb", (f.length() / 1024.0))
                    addProperty("filename", f.name)
                })
            }
        }
        return out
    }

    fun cacheDelete(tf: String, date: String): JsonObject {
        val f = File(cacheDir, "candles_${tf}_${date}.json")
        val ok = f.exists() && f.delete()
        return JsonObject().apply {
            addProperty("ok", ok)
            addProperty("deleted", f.name)
        }
    }

    suspend fun cacheDownload(tf: String, date: String): JsonObject {
        val (from, to) = LocalBotRuntime.gregorianDayRange(date)
        val file = File(cacheDir, "candles_${tf}_${date}.json")
        val before = readCandlesIfExists(file)
        val candles = HivaRoomClient.getBars(tf, from, to)
        file.writeText(candlesToJson(candles))
        logDataAudit(
            source = "cacheDownload",
            date = date,
            tf = tf,
            before = before,
            after = candles
        )
        return JsonObject().apply {
            addProperty("ok", true)
            addProperty("date", date)
            addProperty("tf", tf)
            addProperty("bar_count", candles.size)
            addProperty("filename", file.name)
        }
    }

    suspend fun cacheDownloadMonth(tf: String, year: Int, month: Int): JsonObject {
        val ym = YearMonth.of(year, month)
        var downloaded = 0
        for (d in 1..ym.lengthOfMonth()) {
            val date = ym.atDay(d).format(DateTimeFormatter.ISO_DATE)
            val f = File(cacheDir, "candles_${tf}_${date}.json")
            if (f.exists()) continue
            cacheDownload(tf, date)
            downloaded++
        }
        return JsonObject().apply {
            addProperty("ok", true)
            addProperty("year", year)
            addProperty("month", month)
            addProperty("downloaded", downloaded)
            addProperty("already_cached", ym.lengthOfMonth() - downloaded)
            addProperty("errors", 0)
            addProperty("skipped_days", 0)
        }
    }

    private fun candlesToJson(candles: List<LocalCandle>): String {
        val arr = JsonArray()
        candles.forEach {
            arr.add(JsonObject().apply {
                addProperty("time", it.time)
                addProperty("open", it.open)
                addProperty("high", it.high)
                addProperty("low", it.low)
                addProperty("close", it.close)
            })
        }
        return arr.toString()
    }

    private fun readCandlesIfExists(file: File): List<LocalCandle>? {
        if (!file.exists()) return null
        return try {
            val root = JsonParser.parseString(file.readText())
            if (!root.isJsonArray) return null
            val arr = root.asJsonArray
            buildList {
                for (i in 0 until arr.size()) {
                    val o = arr[i].asJsonObject
                    val time = o.get("time")?.asLong ?: continue
                    val open = o.get("open")?.asDouble ?: continue
                    val high = o.get("high")?.asDouble ?: continue
                    val low = o.get("low")?.asDouble ?: continue
                    val close = o.get("close")?.asDouble ?: continue
                    add(LocalCandle(time, open, high, low, close))
                }
            }
        } catch (_: Exception) {
            null
        }
    }

    private fun expectedCountForTf(tf: String): Int? = when (tf) {
        "1" -> 1440
        "5" -> 288
        "15" -> 96
        "30" -> 48
        "60" -> 24
        else -> null
    }

    private data class CandleDigest(
        val count: Int,
        val firstTime: Long?,
        val lastTime: Long?,
        val firstClose: Double?,
        val lastClose: Double?,
        val strictAscendingTime: Boolean,
        val uniqueTimeCount: Int,
        val signature: Long
    )

    private data class ReferenceDigest(
        val count: Int,
        val firstTime: Long,
        val lastTime: Long,
        val firstClose: Double,
        val lastClose: Double,
        val signature: Long
    )

    private val referenceByDate: Map<String, Map<String, ReferenceDigest>> = mapOf(
        // Web reference dataset: SH-day-1405-01-23 (Gregorian equivalent 2026-04-12)
        "2026-04-12" to mapOf(
            "1" to ReferenceDigest(1440, 1775786880, 1776007800, 79549.0, 79388.0, -3107878900440706963L),
            "5" to ReferenceDigest(288, 1775810100, 1776007800, 79385.0, 79388.0, 4820164964497034569L),
            "15" to ReferenceDigest(96, 1775825100, 1776007800, 79758.0, 79388.0, -728215243182669335L),
            "30" to ReferenceDigest(48, 1775835000, 1776007800, 79593.0, 79388.0, 4616609768932816953L),
            "60" to ReferenceDigest(24, 1775844000, 1776006000, 79657.0, 79388.0, -5683134918221444067L),
        )
    )

    private fun digest(candles: List<LocalCandle>?): CandleDigest? {
        if (candles == null) return null
        if (candles.isEmpty()) {
            return CandleDigest(
                count = 0,
                firstTime = null,
                lastTime = null,
                firstClose = null,
                lastClose = null,
                strictAscendingTime = true,
                uniqueTimeCount = 0,
                signature = 0L
            )
        }
        val strictAscending = candles.zipWithNext().all { (a, b) -> b.time > a.time }
        var sig = 1125899906842597L
        candles.forEach {
            sig = 31L * sig + it.time
            sig = 31L * sig + (it.open * 100.0).roundToLong()
            sig = 31L * sig + (it.high * 100.0).roundToLong()
            sig = 31L * sig + (it.low * 100.0).roundToLong()
            sig = 31L * sig + (it.close * 100.0).roundToLong()
        }
        return CandleDigest(
            count = candles.size,
            firstTime = candles.first().time,
            lastTime = candles.last().time,
            firstClose = candles.first().close,
            lastClose = candles.last().close,
            strictAscendingTime = strictAscending,
            uniqueTimeCount = candles.map { it.time }.toSet().size,
            signature = sig
        )
    }

    private fun logDataAudit(
        source: String,
        date: String,
        tf: String,
        before: List<LocalCandle>?,
        after: List<LocalCandle>
    ) {
        val b = digest(before)
        val a = digest(after) ?: return
        val expected = expectedCountForTf(tf)
        val countMatch = expected == null || a.count == expected
        val integrityOk = a.strictAscendingTime && a.uniqueTimeCount == a.count
        val changed = b?.signature != null && b.signature != a.signature
        val status = if (countMatch && integrityOk) "MATCH" else "MISMATCH"
        val ref = referenceByDate[date]?.get(tf)
        val refMatch = if (ref == null) {
            "n/a"
        } else {
            val ok = a.count == ref.count &&
                a.firstTime == ref.firstTime &&
                a.lastTime == ref.lastTime &&
                a.firstClose == ref.firstClose &&
                a.lastClose == ref.lastClose &&
                a.signature == ref.signature
            if (ok) "MATCH" else "MISMATCH"
        }
        Log.i(
            tag,
            "DATA_AUDIT $status source=$source date=$date tf=${tf}m count=${a.count} expected=${expected ?: "-"} first=${a.firstTime}/${a.firstClose} last=${a.lastTime}/${a.lastClose} ascending=${a.strictAscendingTime} unique=${a.uniqueTimeCount}/${a.count} signature=${a.signature} changed=${if (b == null) "new_file" else changed} ref=$refMatch"
        )
        if (ref != null && refMatch == "MISMATCH") {
            Log.w(
                tag,
                "DATA_AUDIT_REF_DIFF date=$date tf=${tf}m actual_sig=${a.signature} ref_sig=${ref.signature} actual_first=${a.firstTime}/${a.firstClose} ref_first=${ref.firstTime}/${ref.firstClose} actual_last=${a.lastTime}/${a.lastClose} ref_last=${ref.lastTime}/${ref.lastClose}"
            )
        }
    }
}
